AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Experimental graph storage for streak.

Outputs:
  ApiEndpoint:
    Description: "Stage API endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/streak"

Resources:
  PostStreakAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./handler/
      Description: 'Streak API POST handler'
      Policies: AmazonDynamoDBFullAccess
      MemorySize: 128
      Timeout: 6
      Environment:
        Variables:
          GOOGLE_APPLICATION_CREDENTIALS: "streak-service-account.json"
          DATASTORE_PROJECT_ID: "streak-146302"
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /streak
            Method: POST

  GetStreakAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./handler/
      Description: 'Streak API handler'
      Environment:
        Variables:
          GOOGLE_APPLICATION_CREDENTIALS: "streak-service-account.json"
          DATASTORE_PROJECT_ID: "streak-146302"
      # TODO: Should this be read only?
      Policies: AmazonDynamoDBFullAccess
      MemorySize: 128
      Timeout: 6
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /streak
            Method: GET

